'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'fr' | 'en' | 'ar' | 'es' | 'de' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.accommodations': 'Logements',
    'nav.experiences': 'Expériences',
    'nav.help': 'Centre d\'aide',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.become_host': 'Devenir hôte',
    'nav.logout': 'Déconnexion',
    
    // Recherche
    'search.destination': 'Destination',
    'search.search_destination': 'Rechercher une destination',
    'search.arrival': 'Arrivée',
    'search.departure': 'Départ',
    'search.travelers': 'Voyageurs',
    'search.traveler': 'voyageur',
    'search.travelers_plural': 'voyageurs',
    'search.search': 'Rechercher',
    
    // Catégories
    'cat.all': 'Tout',
    'cat.hotels': 'Hôtels',
    'cat.houses': 'Maisons',
    'cat.apartments': 'Appartements',
    'cat.villas': 'Villas',
    
    // Page d'accueil
    'home.no_listings': 'Aucun logement pour l\'instant',
    'home.launching_soon': 'Nous lançons bientôt notre plateforme au Mali ! Soyez parmi les premiers hôtes à rejoindre Ikasso.',
    'home.why_ikasso': 'Pourquoi choisir Ikasso ?',
    'home.secure_booking': 'Réservation sécurisée',
    'home.secure_booking_desc': 'Paiements protégés et données sécurisées',
    'home.support_24_7': 'Support 24/7',
    'home.support_24_7_desc': 'Une équipe disponible à tout moment',
    'home.flexible_payment': 'Paiement flexible',
    'home.flexible_payment_desc': 'Orange Money, carte ou espèces',
    'home.verified_quality': 'Qualité vérifiée',
    'home.verified_quality_desc': 'Hébergements inspectés et validés',
    'home.have_property': 'Vous avez un hébergement à proposer ?',
    'home.join_ikasso': 'Rejoignez Ikasso et commencez à gagner de l\'argent en accueillant des voyageurs',
    'home.get_started': 'Commencer',
    'home.destination_ideas': 'Des idées pour vos prochaines escapades',
    'home.popular': 'Populaire',
    'home.accommodations': 'Hébergements',
    
    // Inscription
    'register.welcome': 'Bienvenue sur Ikasso',
    'register.verify_phone': 'Commençons par vérifier votre numéro',
    'register.i_want_to': 'Je souhaite',
    'register.travel': 'Voyager',
    'register.book_accommodations': 'Réserver des logements',
    'register.host': 'Héberger',
    'register.offer_accommodation': 'Proposer mon logement',
    'register.phone_number': 'Numéro de téléphone',
    'register.receive_code': 'Recevoir le code par SMS',
    'register.verification_code': 'Code de vérification',
    'register.verify': 'Vérifier',
    'register.resend_code': 'Renvoyer le code',
    'register.continue': 'Continuer',
    'register.complete_profile': 'Complétez votre profil',
    'register.back': 'Retour',
    'register.first_name': 'Prénom',
    'register.last_name': 'Nom',
    'register.date_of_birth': 'Date de naissance',
    'register.address': 'Adresse',
    'register.city': 'Ville',
    'register.country': 'Pays',
    'register.email': 'Email',
    'register.password': 'Mot de passe',
    'register.confirm_password': 'Confirmer',
    'register.min_8_chars': 'Minimum 8 caractères',
    'register.verify_email': 'Vérifiez votre email',
    'register.code_will_be_sent': 'Un code sera envoyé',
    'register.send_code': 'Envoyer le code',
    'register.email_verified': 'Email vérifié !',
    'register.create_account': 'Créer mon compte',
    'register.already_registered': 'Déjà inscrit ?',
    'register.terms_accept': 'En vous inscrivant, vous acceptez nos',
    'register.terms': 'Conditions',
    'register.and': 'et notre',
    'register.privacy': 'Politique de confidentialité',
    
    // Connexion
    'login.welcome_back': 'Bon retour !',
    'login.connect_to_account': 'Connectez-vous pour accéder à votre compte',
    'login.email_address': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.remember_me': 'Se souvenir de moi',
    'login.forgot_password': 'Mot de passe oublié ?',
    'login.login': 'Se connecter',
    'login.no_account': 'Pas encore de compte ?',
    'login.continue_google': 'Continuer avec Google',
    'login.continue_apple': 'Continuer avec Apple',
    'login.google_coming_soon': 'La connexion Google sera bientôt disponible',
    'login.apple_coming_soon': 'La connexion Apple sera bientôt disponible',
    'login.or': 'ou',
    
    // Centre d'aide
    'help.title': 'Centre d\'aide Ikasso',
    'help.subtitle': 'Trouvez rapidement des réponses à vos questions ou contactez notre équipe support',
    'help.search_placeholder': 'Rechercher dans l\'aide...',
    'help.live_chat': 'Chat en direct',
    'help.live_chat_desc': 'Chattez avec notre équipe support pour une aide immédiate',
    'help.call_us': 'Nous appeler',
    'help.send_email': 'Envoyer un email',
    'help.response_24h': 'Réponse sous 24h',
    'help.categories': 'Catégories',
    'help.all_categories': 'Toutes les catégories',
    'help.bookings': 'Réservations',
    'help.payments': 'Paiements',
    'help.account': 'Compte',
    'help.safety': 'Sécurité',
    'help.hosts': 'Hôtes',
    'help.faq': 'Questions fréquentes',
    'help.no_results': 'Aucun résultat trouvé',
    'help.try_different_search': 'Essayez de modifier votre recherche ou contactez notre support.',
    'help.need_more_help': 'Besoin d\'aide supplémentaire ?',
    'help.didnt_find_answer': 'Vous n\'avez pas trouvé votre réponse ?',
    'help.team_available': 'Notre équipe support est là pour vous aider',
    'help.contact_support': 'Contacter le support',
    'help.back_home': 'Retour à l\'accueil',
    
    // Footer
    'footer.support': 'Assistance',
    'footer.help_center': 'Centre d\'aide',
    'footer.safety_support': 'Assistance sécurité',
    'footer.cancellation_options': 'Options d\'annulation',
    'footer.hosting': 'Accueil de voyageurs',
    'footer.list_property': 'Mettez votre logement sur Ikasso',
    'footer.host_resources': 'Ressources pour les hôtes',
    'footer.community_forum': 'Forum de la communauté',
    'footer.newsroom': 'Newsroom',
    'footer.careers': 'Carrières',
    'footer.investors': 'Investisseurs',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions générales',
    
    // Cookies
    'cookies.title': 'Nous utilisons des cookies',
    'cookies.description': 'Ce site utilise des cookies pour améliorer votre expérience. En continuant à naviguer, vous acceptez notre utilisation des cookies.',
    'cookies.accept': 'Accepter',
    'cookies.decline': 'Refuser',
    'cookies.manage': 'Gérer les préférences',
    'cookies.learn_more': 'En savoir plus',
    
    // Général
    'general.loading': 'Chargement...',
    'general.error': 'Erreur',
    'general.success': 'Succès',
    'general.save': 'Enregistrer',
    'general.cancel': 'Annuler',
    'general.close': 'Fermer',
    'general.new': 'NOUVEAU',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.accommodations': 'Accommodations',
    'nav.experiences': 'Experiences',
    'nav.help': 'Help Center',
    'nav.login': 'Log in',
    'nav.signup': 'Sign up',
    'nav.become_host': 'Become a host',
    'nav.logout': 'Log out',
    
    // Search
    'search.destination': 'Destination',
    'search.search_destination': 'Search destinations',
    'search.arrival': 'Check in',
    'search.departure': 'Check out',
    'search.travelers': 'Guests',
    'search.traveler': 'guest',
    'search.travelers_plural': 'guests',
    'search.search': 'Search',
    
    // Categories
    'cat.all': 'All',
    'cat.hotels': 'Hotels',
    'cat.houses': 'Houses',
    'cat.apartments': 'Apartments',
    'cat.villas': 'Villas',
    
    // Home page
    'home.no_listings': 'No listings yet',
    'home.launching_soon': 'We are launching soon in Mali! Be among the first hosts to join Ikasso.',
    'home.why_ikasso': 'Why choose Ikasso?',
    'home.secure_booking': 'Secure booking',
    'home.secure_booking_desc': 'Protected payments and secure data',
    'home.support_24_7': '24/7 Support',
    'home.support_24_7_desc': 'A team available at all times',
    'home.flexible_payment': 'Flexible payment',
    'home.flexible_payment_desc': 'Orange Money, card or cash',
    'home.verified_quality': 'Verified quality',
    'home.verified_quality_desc': 'Inspected and validated accommodations',
    'home.have_property': 'Do you have a property to offer?',
    'home.join_ikasso': 'Join Ikasso and start earning money by hosting travelers',
    'home.get_started': 'Get started',
    'home.destination_ideas': 'Ideas for your next getaway',
    'home.popular': 'Popular',
    'home.accommodations': 'Accommodations',
    
    // Registration
    'register.welcome': 'Welcome to Ikasso',
    'register.verify_phone': 'Let\'s start by verifying your number',
    'register.i_want_to': 'I want to',
    'register.travel': 'Travel',
    'register.book_accommodations': 'Book accommodations',
    'register.host': 'Host',
    'register.offer_accommodation': 'Offer my accommodation',
    'register.phone_number': 'Phone number',
    'register.receive_code': 'Receive code by SMS',
    'register.verification_code': 'Verification code',
    'register.verify': 'Verify',
    'register.resend_code': 'Resend code',
    'register.continue': 'Continue',
    'register.complete_profile': 'Complete your profile',
    'register.back': 'Back',
    'register.first_name': 'First name',
    'register.last_name': 'Last name',
    'register.date_of_birth': 'Date of birth',
    'register.address': 'Address',
    'register.city': 'City',
    'register.country': 'Country',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.confirm_password': 'Confirm',
    'register.min_8_chars': 'Minimum 8 characters',
    'register.verify_email': 'Verify your email',
    'register.code_will_be_sent': 'A code will be sent',
    'register.send_code': 'Send code',
    'register.email_verified': 'Email verified!',
    'register.create_account': 'Create my account',
    'register.already_registered': 'Already registered?',
    'register.terms_accept': 'By signing up, you agree to our',
    'register.terms': 'Terms',
    'register.and': 'and our',
    'register.privacy': 'Privacy Policy',
    
    // Login
    'login.welcome_back': 'Welcome back!',
    'login.connect_to_account': 'Log in to access your account',
    'login.email_address': 'Email address',
    'login.password': 'Password',
    'login.remember_me': 'Remember me',
    'login.forgot_password': 'Forgot password?',
    'login.login': 'Log in',
    'login.no_account': 'Don\'t have an account?',
    'login.continue_google': 'Continue with Google',
    'login.continue_apple': 'Continue with Apple',
    'login.google_coming_soon': 'Google login coming soon',
    'login.apple_coming_soon': 'Apple login coming soon',
    'login.or': 'or',
    
    // Help Center
    'help.title': 'Ikasso Help Center',
    'help.subtitle': 'Quickly find answers to your questions or contact our support team',
    'help.search_placeholder': 'Search help...',
    'help.live_chat': 'Live chat',
    'help.live_chat_desc': 'Chat with our support team for immediate help',
    'help.call_us': 'Call us',
    'help.send_email': 'Send an email',
    'help.response_24h': 'Response within 24h',
    'help.categories': 'Categories',
    'help.all_categories': 'All categories',
    'help.bookings': 'Bookings',
    'help.payments': 'Payments',
    'help.account': 'Account',
    'help.safety': 'Safety',
    'help.hosts': 'Hosts',
    'help.faq': 'Frequently asked questions',
    'help.no_results': 'No results found',
    'help.try_different_search': 'Try modifying your search or contact our support.',
    'help.need_more_help': 'Need more help?',
    'help.didnt_find_answer': 'Didn\'t find your answer?',
    'help.team_available': 'Our support team is here to help you',
    'help.contact_support': 'Contact support',
    'help.back_home': 'Back to home',
    
    // Footer
    'footer.support': 'Support',
    'footer.help_center': 'Help Center',
    'footer.safety_support': 'Safety support',
    'footer.cancellation_options': 'Cancellation options',
    'footer.hosting': 'Hosting',
    'footer.list_property': 'List your property on Ikasso',
    'footer.host_resources': 'Host resources',
    'footer.community_forum': 'Community forum',
    'footer.newsroom': 'Newsroom',
    'footer.careers': 'Careers',
    'footer.investors': 'Investors',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    
    // Cookies
    'cookies.title': 'We use cookies',
    'cookies.description': 'This site uses cookies to improve your experience. By continuing to browse, you accept our use of cookies.',
    'cookies.accept': 'Accept',
    'cookies.decline': 'Decline',
    'cookies.manage': 'Manage preferences',
    'cookies.learn_more': 'Learn more',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    'general.close': 'Close',
    'general.new': 'NEW',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.accommodations': 'أماكن الإقامة',
    'nav.experiences': 'التجارب',
    'nav.help': 'مركز المساعدة',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'التسجيل',
    'nav.become_host': 'كن مضيفًا',
    'nav.logout': 'تسجيل الخروج',
    
    // Search
    'search.destination': 'الوجهة',
    'search.search_destination': 'ابحث عن وجهة',
    'search.arrival': 'الوصول',
    'search.departure': 'المغادرة',
    'search.travelers': 'المسافرون',
    'search.traveler': 'مسافر',
    'search.travelers_plural': 'مسافرين',
    'search.search': 'بحث',
    
    // Categories
    'cat.all': 'الكل',
    'cat.hotels': 'فنادق',
    'cat.houses': 'منازل',
    'cat.apartments': 'شقق',
    'cat.villas': 'فيلات',
    
    // Home
    'home.no_listings': 'لا توجد إقامات حاليًا',
    'home.launching_soon': 'نطلق قريبًا في مالي! كن من أوائل المضيفين في إيكاسو.',
    'home.why_ikasso': 'لماذا إيكاسو؟',
    'home.secure_booking': 'حجز آمن',
    'home.secure_booking_desc': 'مدفوعات محمية وبيانات آمنة',
    'home.support_24_7': 'دعم 24/7',
    'home.support_24_7_desc': 'فريق متاح في أي وقت',
    'home.flexible_payment': 'دفع مرن',
    'home.flexible_payment_desc': 'أورانج موني، بطاقة أو نقدًا',
    'home.verified_quality': 'جودة موثقة',
    'home.verified_quality_desc': 'إقامات مفحوصة ومعتمدة',
    'home.have_property': 'هل لديك عقار للعرض؟',
    'home.join_ikasso': 'انضم إلى إيكاسو وابدأ في كسب المال باستضافة المسافرين',
    'home.get_started': 'ابدأ الآن',
    'home.destination_ideas': 'أفكار لرحلتك القادمة',
    'home.popular': 'شائع',
    'home.accommodations': 'أماكن الإقامة',
    
    // Registration
    'register.welcome': 'مرحبًا بك في إيكاسو',
    'register.verify_phone': 'لنبدأ بالتحقق من رقمك',
    'register.i_want_to': 'أريد',
    'register.travel': 'السفر',
    'register.book_accommodations': 'حجز أماكن إقامة',
    'register.host': 'الاستضافة',
    'register.offer_accommodation': 'عرض مكان إقامتي',
    'register.phone_number': 'رقم الهاتف',
    'register.receive_code': 'استلام الرمز عبر SMS',
    'register.verification_code': 'رمز التحقق',
    'register.verify': 'تحقق',
    'register.resend_code': 'إعادة إرسال الرمز',
    'register.continue': 'متابعة',
    'register.complete_profile': 'أكمل ملفك الشخصي',
    'register.back': 'رجوع',
    'register.first_name': 'الاسم الأول',
    'register.last_name': 'اسم العائلة',
    'register.date_of_birth': 'تاريخ الميلاد',
    'register.address': 'العنوان',
    'register.city': 'المدينة',
    'register.country': 'البلد',
    'register.email': 'البريد الإلكتروني',
    'register.password': 'كلمة المرور',
    'register.confirm_password': 'تأكيد',
    'register.min_8_chars': '8 أحرف على الأقل',
    'register.verify_email': 'تحقق من بريدك الإلكتروني',
    'register.code_will_be_sent': 'سيتم إرسال رمز',
    'register.send_code': 'إرسال الرمز',
    'register.email_verified': 'تم التحقق من البريد!',
    'register.create_account': 'إنشاء حسابي',
    'register.already_registered': 'لديك حساب؟',
    'register.terms_accept': 'بالتسجيل، أنت توافق على',
    'register.terms': 'الشروط',
    'register.and': 'و',
    'register.privacy': 'سياسة الخصوصية',
    
    // Login
    'login.welcome_back': 'مرحبًا بعودتك!',
    'login.connect_to_account': 'سجل الدخول للوصول إلى حسابك',
    'login.email_address': 'عنوان البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.remember_me': 'تذكرني',
    'login.forgot_password': 'نسيت كلمة المرور؟',
    'login.login': 'تسجيل الدخول',
    'login.no_account': 'ليس لديك حساب؟',
    'login.continue_google': 'المتابعة مع Google',
    'login.continue_apple': 'المتابعة مع Apple',
    'login.google_coming_soon': 'تسجيل الدخول بـ Google قريبًا',
    'login.apple_coming_soon': 'تسجيل الدخول بـ Apple قريبًا',
    'login.or': 'أو',
    
    // Help
    'help.title': 'مركز مساعدة إيكاسو',
    'help.subtitle': 'ابحث عن إجابات لأسئلتك أو تواصل مع فريق الدعم',
    'help.search_placeholder': 'البحث في المساعدة...',
    'help.live_chat': 'محادثة مباشرة',
    'help.live_chat_desc': 'تحدث مع فريق الدعم للمساعدة الفورية',
    'help.call_us': 'اتصل بنا',
    'help.send_email': 'أرسل بريدًا إلكترونيًا',
    'help.response_24h': 'الرد خلال 24 ساعة',
    'help.categories': 'الفئات',
    'help.all_categories': 'جميع الفئات',
    'help.bookings': 'الحجوزات',
    'help.payments': 'المدفوعات',
    'help.account': 'الحساب',
    'help.safety': 'الأمان',
    'help.hosts': 'المضيفون',
    'help.faq': 'الأسئلة الشائعة',
    'help.no_results': 'لم يتم العثور على نتائج',
    'help.try_different_search': 'جرب تعديل بحثك أو تواصل مع الدعم.',
    'help.need_more_help': 'تحتاج مساعدة إضافية؟',
    'help.didnt_find_answer': 'لم تجد إجابتك؟',
    'help.team_available': 'فريق الدعم هنا لمساعدتك',
    'help.contact_support': 'تواصل مع الدعم',
    'help.back_home': 'العودة للرئيسية',
    
    // Footer
    'footer.support': 'الدعم',
    'footer.help_center': 'مركز المساعدة',
    'footer.safety_support': 'دعم الأمان',
    'footer.cancellation_options': 'خيارات الإلغاء',
    'footer.hosting': 'الاستضافة',
    'footer.list_property': 'أضف عقارك على إيكاسو',
    'footer.host_resources': 'موارد المضيفين',
    'footer.community_forum': 'منتدى المجتمع',
    'footer.newsroom': 'غرفة الأخبار',
    'footer.careers': 'الوظائف',
    'footer.investors': 'المستثمرون',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    
    // Cookies
    'cookies.title': 'نحن نستخدم ملفات تعريف الارتباط',
    'cookies.description': 'يستخدم هذا الموقع ملفات تعريف الارتباط لتحسين تجربتك. بالمتابعة، أنت توافق على استخدامنا لها.',
    'cookies.accept': 'قبول',
    'cookies.decline': 'رفض',
    'cookies.manage': 'إدارة التفضيلات',
    'cookies.learn_more': 'معرفة المزيد',
    
    // General
    'general.loading': 'جاري التحميل...',
    'general.error': 'خطأ',
    'general.success': 'نجاح',
    'general.save': 'حفظ',
    'general.cancel': 'إلغاء',
    'general.close': 'إغلاق',
    'general.new': 'جديد',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.accommodations': 'Alojamientos',
    'nav.experiences': 'Experiencias',
    'nav.help': 'Centro de ayuda',
    'nav.login': 'Iniciar sesión',
    'nav.signup': 'Registrarse',
    'nav.become_host': 'Ser anfitrión',
    'nav.logout': 'Cerrar sesión',
    
    // Search
    'search.destination': 'Destino',
    'search.search_destination': 'Buscar destino',
    'search.arrival': 'Llegada',
    'search.departure': 'Salida',
    'search.travelers': 'Viajeros',
    'search.traveler': 'viajero',
    'search.travelers_plural': 'viajeros',
    'search.search': 'Buscar',
    
    // Categories
    'cat.all': 'Todo',
    'cat.hotels': 'Hoteles',
    'cat.houses': 'Casas',
    'cat.apartments': 'Apartamentos',
    'cat.villas': 'Villas',
    
    // Home
    'home.no_listings': 'Sin alojamientos por ahora',
    'home.launching_soon': '¡Pronto lanzamos en Malí! Sé de los primeros anfitriones en unirse a Ikasso.',
    'home.why_ikasso': '¿Por qué elegir Ikasso?',
    'home.secure_booking': 'Reserva segura',
    'home.secure_booking_desc': 'Pagos protegidos y datos seguros',
    'home.support_24_7': 'Soporte 24/7',
    'home.support_24_7_desc': 'Un equipo disponible en todo momento',
    'home.flexible_payment': 'Pago flexible',
    'home.flexible_payment_desc': 'Orange Money, tarjeta o efectivo',
    'home.verified_quality': 'Calidad verificada',
    'home.verified_quality_desc': 'Alojamientos inspeccionados y validados',
    'home.have_property': '¿Tienes un alojamiento para ofrecer?',
    'home.join_ikasso': 'Únete a Ikasso y empieza a ganar dinero hospedando viajeros',
    'home.get_started': 'Comenzar',
    'home.destination_ideas': 'Ideas para tu próxima escapada',
    'home.popular': 'Popular',
    'home.accommodations': 'Alojamientos',
    
    // Register
    'register.welcome': 'Bienvenido a Ikasso',
    'register.verify_phone': 'Empecemos verificando tu número',
    'register.i_want_to': 'Quiero',
    'register.travel': 'Viajar',
    'register.book_accommodations': 'Reservar alojamientos',
    'register.host': 'Hospedar',
    'register.offer_accommodation': 'Ofrecer mi alojamiento',
    'register.phone_number': 'Número de teléfono',
    'register.receive_code': 'Recibir código por SMS',
    'register.verification_code': 'Código de verificación',
    'register.verify': 'Verificar',
    'register.resend_code': 'Reenviar código',
    'register.continue': 'Continuar',
    'register.complete_profile': 'Completa tu perfil',
    'register.back': 'Volver',
    'register.first_name': 'Nombre',
    'register.last_name': 'Apellido',
    'register.date_of_birth': 'Fecha de nacimiento',
    'register.address': 'Dirección',
    'register.city': 'Ciudad',
    'register.country': 'País',
    'register.email': 'Correo',
    'register.password': 'Contraseña',
    'register.confirm_password': 'Confirmar',
    'register.min_8_chars': 'Mínimo 8 caracteres',
    'register.verify_email': 'Verifica tu correo',
    'register.code_will_be_sent': 'Se enviará un código',
    'register.send_code': 'Enviar código',
    'register.email_verified': '¡Correo verificado!',
    'register.create_account': 'Crear mi cuenta',
    'register.already_registered': '¿Ya registrado?',
    'register.terms_accept': 'Al registrarte, aceptas nuestros',
    'register.terms': 'Términos',
    'register.and': 'y nuestra',
    'register.privacy': 'Política de privacidad',
    
    // Login
    'login.welcome_back': '¡Bienvenido de nuevo!',
    'login.connect_to_account': 'Inicia sesión para acceder a tu cuenta',
    'login.email_address': 'Correo electrónico',
    'login.password': 'Contraseña',
    'login.remember_me': 'Recordarme',
    'login.forgot_password': '¿Olvidaste tu contraseña?',
    'login.login': 'Iniciar sesión',
    'login.no_account': '¿No tienes cuenta?',
    'login.continue_google': 'Continuar con Google',
    'login.continue_apple': 'Continuar con Apple',
    'login.google_coming_soon': 'Inicio con Google próximamente',
    'login.apple_coming_soon': 'Inicio con Apple próximamente',
    'login.or': 'o',
    
    // Help
    'help.title': 'Centro de ayuda Ikasso',
    'help.subtitle': 'Encuentra respuestas rápidas o contacta con nuestro equipo de soporte',
    'help.search_placeholder': 'Buscar en ayuda...',
    'help.live_chat': 'Chat en vivo',
    'help.live_chat_desc': 'Chatea con nuestro equipo para ayuda inmediata',
    'help.call_us': 'Llámanos',
    'help.send_email': 'Enviar correo',
    'help.response_24h': 'Respuesta en 24h',
    'help.categories': 'Categorías',
    'help.all_categories': 'Todas las categorías',
    'help.bookings': 'Reservas',
    'help.payments': 'Pagos',
    'help.account': 'Cuenta',
    'help.safety': 'Seguridad',
    'help.hosts': 'Anfitriones',
    'help.faq': 'Preguntas frecuentes',
    'help.no_results': 'Sin resultados',
    'help.try_different_search': 'Intenta modificar tu búsqueda o contacta con soporte.',
    'help.need_more_help': '¿Necesitas más ayuda?',
    'help.didnt_find_answer': '¿No encontraste tu respuesta?',
    'help.team_available': 'Nuestro equipo está aquí para ayudarte',
    'help.contact_support': 'Contactar soporte',
    'help.back_home': 'Volver al inicio',
    
    // Footer
    'footer.support': 'Soporte',
    'footer.help_center': 'Centro de ayuda',
    'footer.safety_support': 'Soporte de seguridad',
    'footer.cancellation_options': 'Opciones de cancelación',
    'footer.hosting': 'Hospedaje',
    'footer.list_property': 'Publica tu propiedad en Ikasso',
    'footer.host_resources': 'Recursos para anfitriones',
    'footer.community_forum': 'Foro de la comunidad',
    'footer.newsroom': 'Noticias',
    'footer.careers': 'Carreras',
    'footer.investors': 'Inversores',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    
    // Cookies
    'cookies.title': 'Usamos cookies',
    'cookies.description': 'Este sitio usa cookies para mejorar tu experiencia. Al continuar, aceptas nuestro uso de cookies.',
    'cookies.accept': 'Aceptar',
    'cookies.decline': 'Rechazar',
    'cookies.manage': 'Gestionar preferencias',
    'cookies.learn_more': 'Más información',
    
    // General
    'general.loading': 'Cargando...',
    'general.error': 'Error',
    'general.success': 'Éxito',
    'general.save': 'Guardar',
    'general.cancel': 'Cancelar',
    'general.close': 'Cerrar',
    'general.new': 'NUEVO',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.accommodations': 'Unterkünfte',
    'nav.experiences': 'Erlebnisse',
    'nav.help': 'Hilfe-Center',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',
    'nav.become_host': 'Gastgeber werden',
    'nav.logout': 'Abmelden',
    'search.destination': 'Reiseziel',
    'search.search_destination': 'Reiseziel suchen',
    'search.arrival': 'Anreise',
    'search.departure': 'Abreise',
    'search.travelers': 'Gäste',
    'search.traveler': 'Gast',
    'search.travelers_plural': 'Gäste',
    'search.search': 'Suchen',
    'cat.all': 'Alle',
    'cat.hotels': 'Hotels',
    'cat.houses': 'Häuser',
    'cat.apartments': 'Apartments',
    'cat.villas': 'Villen',
    'home.no_listings': 'Noch keine Unterkünfte',
    'home.launching_soon': 'Wir starten bald in Mali! Seien Sie einer der ersten Gastgeber bei Ikasso.',
    'home.why_ikasso': 'Warum Ikasso wählen?',
    'home.secure_booking': 'Sichere Buchung',
    'home.secure_booking_desc': 'Geschützte Zahlungen und sichere Daten',
    'home.support_24_7': '24/7 Support',
    'home.support_24_7_desc': 'Ein Team, das jederzeit verfügbar ist',
    'home.flexible_payment': 'Flexible Zahlung',
    'home.flexible_payment_desc': 'Orange Money, Karte oder Bargeld',
    'home.verified_quality': 'Geprüfte Qualität',
    'home.verified_quality_desc': 'Geprüfte und validierte Unterkünfte',
    'home.have_property': 'Haben Sie eine Unterkunft anzubieten?',
    'home.join_ikasso': 'Treten Sie Ikasso bei und verdienen Sie Geld mit Gästen',
    'home.get_started': 'Loslegen',
    'home.destination_ideas': 'Ideen für Ihren nächsten Ausflug',
    'home.popular': 'Beliebt',
    'home.accommodations': 'Unterkünfte',
    'cookies.title': 'Wir verwenden Cookies',
    'cookies.description': 'Diese Website verwendet Cookies, um Ihre Erfahrung zu verbessern. Durch das Fortfahren akzeptieren Sie unsere Verwendung von Cookies.',
    'cookies.accept': 'Akzeptieren',
    'cookies.decline': 'Ablehnen',
    'cookies.manage': 'Einstellungen verwalten',
    'cookies.learn_more': 'Mehr erfahren',
    'general.loading': 'Laden...',
    'general.error': 'Fehler',
    'general.success': 'Erfolg',
    'general.save': 'Speichern',
    'general.cancel': 'Abbrechen',
    'general.close': 'Schließen',
    'general.new': 'NEU',
  },
  zh: {
    'nav.home': '首页',
    'nav.accommodations': '住宿',
    'nav.experiences': '体验',
    'nav.help': '帮助中心',
    'nav.login': '登录',
    'nav.signup': '注册',
    'nav.become_host': '成为房东',
    'nav.logout': '退出',
    'search.destination': '目的地',
    'search.search_destination': '搜索目的地',
    'search.arrival': '入住',
    'search.departure': '退房',
    'search.travelers': '旅客',
    'search.traveler': '位旅客',
    'search.travelers_plural': '位旅客',
    'search.search': '搜索',
    'cat.all': '全部',
    'cat.hotels': '酒店',
    'cat.houses': '房屋',
    'cat.apartments': '公寓',
    'cat.villas': '别墅',
    'home.no_listings': '暂无房源',
    'home.launching_soon': '我们即将在马里启动！成为Ikasso的首批房东。',
    'home.why_ikasso': '为什么选择Ikasso？',
    'home.secure_booking': '安全预订',
    'home.secure_booking_desc': '受保护的支付和安全数据',
    'home.support_24_7': '24/7支持',
    'home.support_24_7_desc': '随时可用的团队',
    'home.flexible_payment': '灵活支付',
    'home.flexible_payment_desc': 'Orange Money、银行卡或现金',
    'home.verified_quality': '品质认证',
    'home.verified_quality_desc': '经过检查和验证的住宿',
    'home.have_property': '有房源要出租？',
    'home.join_ikasso': '加入Ikasso，接待旅客赚取收入',
    'home.get_started': '开始',
    'home.destination_ideas': '下次旅行的灵感',
    'home.popular': '热门',
    'home.accommodations': '住宿',
    'cookies.title': '我们使用Cookie',
    'cookies.description': '本网站使用Cookie来改善您的体验。继续浏览即表示您接受我们使用Cookie。',
    'cookies.accept': '接受',
    'cookies.decline': '拒绝',
    'cookies.manage': '管理偏好',
    'cookies.learn_more': '了解更多',
    'general.loading': '加载中...',
    'general.error': '错误',
    'general.success': '成功',
    'general.save': '保存',
    'general.cancel': '取消',
    'general.close': '关闭',
    'general.new': '新',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr')

  useEffect(() => {
    const savedLang = localStorage.getItem('ikasso_language') as Language
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('ikasso_language', lang)
    // Pour l'arabe, on ajoute direction RTL
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl'
    } else {
      document.documentElement.dir = 'ltr'
    }
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['fr'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const availableLanguages = [
  { code: 'fr', name: 'Français', flag: '🇫🇷', region: 'France' },
  { code: 'en', name: 'English', flag: '🇬🇧', region: 'United Kingdom' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', region: 'العالم العربي' },
  { code: 'es', name: 'Español', flag: '🇪🇸', region: 'España' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', region: 'Deutschland' },
  { code: 'zh', name: '中文', flag: '🇨🇳', region: '中国' },
]





